/**
 * @author Vad Nik
 * @version 0.2.3 dated Jan 17, 2018
 */
import java.io.*;
import java.net.*;
import java.sql.*;
import java.util.Scanner;
/*
Modified for server can does a broadcast and you can now quit the server.


I didn't fully understand what means the broadcast, more precisely, what do you want I have to do, but I did it,
but don't thing I do it as you like to do it, but everything works for me.


I didn't find the [JDK]\jre\lib\ext, so I found the tutorial to make connection with sql and I do it, I guess, the right way and it works.
I don't know why I haven't this path, maybe because I have JDK 9 and JRE 9.
 */
class SimpleServer implements IConstants {

    boolean isDefault;
    String br;

    public static void main(String[] args) {
        new SimpleServer();
    }

    void editBroadcast() {
        Scanner sc = new Scanner(System.in);
        System.out.println("\nType 1 to edit the broadcast, type 2 to set it default.\n" +
                "DO IT BEFORE YOU RUN THE CLIENT!!!");
        if (sc.nextLine().equals("1")) {
            System.out.println("Type your broadcast below: ");
            br = sc.nextLine();
            isDefault = false;
        } else if (sc.nextLine().equals("2")) {
            isDefault = true;
        } else if (sc.nextLine().equals(EXIT_COMMAND)) {
            System.exit(0);
        }
    }

    SimpleServer() {
        editBroadcast();
        exit();
        int clientCount = 0;
        System.out.println(SERVER_START);
        try (ServerSocket server = new ServerSocket(SERVER_PORT)) {
            while (true) {
                Socket socket = server.accept();
                System.out.println("#" + (++clientCount) + CLIENT_JOINED);
                new Thread(new ClientHandler(socket, clientCount)).start();
            } 
        } catch (Exception ex) {
            System.out.println(ex.getMessage());
        }
        System.out.println(SERVER_STOP);
    }

    void exit() {
        System.out.println("Now you can quit the server by typing 'exit'.");
        new Thread(new Exit()).start();
    }

    /**
     * checkAuthentication: check login and password
     *
     * @param  login for checking
     * @param  passwd for checking
     *
     * @return if the pair login/passwd is found in the database,
     *         authentication is successful
     */
    boolean checkAuthentication(String login, String passwd) {
        boolean result = false;
        try {
            // loads a class, including running its static initializers
            Class.forName(DRIVER_NAME);
            // connect db
            Connection connect = DriverManager.getConnection(SQLITE_DB);
            // looking for login && passwd in db
            PreparedStatement pstmt = connect.prepareStatement(SQL_SELECT);
            // replace "?" to the login
            pstmt.setString(1, login);
            // returns ResultSet object generated by the query
            ResultSet rs = pstmt.executeQuery();
            // process rows from the query result
            while (rs.next())
                result = rs.getString(PASSWD_COL).equals(passwd);
            // close all
            rs.close();
            pstmt.close();
            connect.close();
        } catch (ClassNotFoundException | SQLException ex) {
            ex.printStackTrace();
            return false;
        }
        return result;
    }

    /**
     * ClientHandler: service requests of clients
     */
    class ClientHandler implements Runnable, IConstants {
        BufferedReader reader;
        PrintWriter writer;
        Socket socket;
        String name;

        ClientHandler(Socket clientSocket, int clientCount) {
            try {
                socket = clientSocket;
                reader = new BufferedReader(
                        new InputStreamReader(socket.getInputStream()));
                writer = new PrintWriter(socket.getOutputStream());
                name = "Client #" + clientCount;
            } catch(Exception ex) {
                System.out.println(ex.getMessage());
            }
        }

        @Override
        public void run() {
            String message;
            try {
                do {
                    message = reader.readLine();
                    if (message != null) {
                        System.out.println(name + ": " + message);
                        if (message.startsWith(AUTH_SIGN)) {
                            String[] wds = message.split(" ");
                            if (checkAuthentication(wds[1], wds[2])) {
                                name = wds[1];
                                defaultBroadcast(name);
                                broadcast(name);
                                writer.println("Hello, " + name);
                                writer.println("\0");
                            } else {
                                System.out.println(name + ": " + AUTH_FAIL);
                                writer.println(AUTH_FAIL);
                                message = EXIT_COMMAND;
                            }
                        } else if (!message.equalsIgnoreCase(EXIT_COMMAND)) {
                            writer.println("echo: " + message);
                            writer.println("\0");
                        }
                        writer.flush();
                    }
                } while (!message.equalsIgnoreCase(EXIT_COMMAND));
                socket.close();
                System.out.println(name + CLIENT_DISCONNECTED);
            } catch(Exception ex) {
                System.out.println(ex.getMessage());
            }
        }

        void defaultBroadcast(String name) {
            if (isDefault) {
                br = "Greetings, " + name + ". This is a broadcast.";
            }
        }

        void broadcast(String name) {
            System.out.println("The broadcast has been sent to " + name);
            writer.println(br);
        }
    }

    class Exit implements Runnable {

        @Override
        public void run() {
            Scanner sc = new Scanner(System.in);
            if (sc.nextLine().equals(EXIT_COMMAND))
                System.exit(0);
        }
    }
}