services:
  webapp:
    build: .
    ports:
      - 8080:8080
    container_name: virt3web
  db:
    image: postgres:14.1-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=db
    ports:
      - '5432:5432'
    container_name: virt3db
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db: